export const strings = {
  x_axis_data_key: '_id',

  eth_graph_title: 'Eth Gas Station',
  eth_data_label: 'Gwei x 10',
  eth_fastest_data_key: 'data.fastest',
  eth_fast_data_key: 'data.fast',
  eth_average_data_key: 'data.average',
  eth_safelow_data_key: 'data.safeLow',
  eth_fastest_data_name: 'Fastest Block Delay',
  eth_fast_data_name: 'Fast Block Delay',
  eth_average_data_name: 'Average Block Delay',
  eth_safelow_data_name: 'Safe Low Block Delay',

  mempool_graph_title: 'Mempool.Space',
  mempool_data_label: 'satoshis/vbyte',
  mempool_fastest_data_key: 'data.fastestFee',
  mempool_half_hour_data_key: 'data.halfHourFee',
  mempool_hour_data_key: 'data.HourFee',
  mempool_minimum_data_key: 'data.minimumFee',
  mempool_fastest_data_name: 'Fastest Block Delay',
  mempool_half_hour_data_name: 'Half Hour Block Delay',
  mempool_hour_data_name: 'Hour Block Delay',
  mempool_minimum_data_name: 'Minimum Fee Block Delay',

  earn_graph_title: 'Earn',
  earn_data_label: 'satoshis/byte',
  earn_zero_to_one_data_key: 'data.sortedData.zeroToOne',
  earn_one_to_two_data_key: 'data.sortedData.oneToTwo',
  earn_two_to_three_data_key: 'data.sortedData.twoToThree',
  earn_three_to_ten_data_key: 'data.sortedData.threeToTen',
  earn_zero_to_one_data_name: '0-1 Block Delay',
  earn_one_to_two_data_name: '1-2 Block Delay',
  earn_two_to_three_data_name: '2-3 Block Delay',
  earn_three_to_ten_data_name: '3-10 Block Delay'
}
